[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "curl", "python3"]

[phases.build]
cmds = ["npm install", "curl -sL https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && chmod +x /usr/local/bin/yt-dlp && echo 'yt-dlp installed'"]

[start]
cmd = "node server.js"
